# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'angbotsvorlage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_AngWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1040, 690)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PDFG_btn = QtWidgets.QPushButton(self.centralwidget)
        self.PDFG_btn.setGeometry(QtCore.QRect(830, 570, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.PDFG_btn.setFont(font)
        self.PDFG_btn.setObjectName("PDFG_btn")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 311, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 90, 451, 89))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.horizontalLayoutWidget_5.setFont(font)
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.Bez_te = QtWidgets.QTextEdit(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.Bez_te.setFont(font)
        self.Bez_te.setObjectName("Bez_te")
        self.horizontalLayout.addWidget(self.Bez_te)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(330, 30, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.horizontalLayoutWidget_6.setFont(font)
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.Nr_le = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.Nr_le.setFont(font)
        self.Nr_le.setObjectName("Nr_le")
        self.horizontalLayout_3.addWidget(self.Nr_le)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 180, 172, 80))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Gd_cbox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.Gd_cbox.setFont(font)
        self.Gd_cbox.setObjectName("Gd_cbox")
        self.Gd_cbox.addItem("")
        self.Gd_cbox.addItem("")
        self.horizontalLayout_4.addWidget(self.Gd_cbox)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 180, 271, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.horizontalLayoutWidget_8.setFont(font)
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.AnlD_de = QtWidgets.QDateEdit(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setUnderline(False)
        self.AnlD_de.setFont(font)
        self.AnlD_de.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 1, 1), QtCore.QTime(0, 0, 0)))
        self.AnlD_de.setCalendarPopup(True)
        self.AnlD_de.setObjectName("AnlD_de")
        self.horizontalLayout_5.addWidget(self.AnlD_de)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(500, 0, 310, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(460, 10, 16, 631))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(470, 10, 16, 631))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(500, 70, 501, 261))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.verticalLayoutWidget_2.setFont(font)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_18.addWidget(self.label_20)
        self.titel_cbox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.titel_cbox.setFont(font)
        self.titel_cbox.setObjectName("titel_cbox")
        self.titel_cbox.addItem("")
        self.titel_cbox.addItem("")
        self.titel_cbox.setItemText(1, "")
        self.titel_cbox.addItem("")
        self.titel_cbox.addItem("")
        self.horizontalLayout_18.addWidget(self.titel_cbox)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_18)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.KdVN_le = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.KdVN_le.setFont(font)
        self.KdVN_le.setObjectName("KdVN_le")
        self.horizontalLayout_9.addWidget(self.KdVN_le)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.KdNN_le = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.KdNN_le.setFont(font)
        self.KdNN_le.setObjectName("KdNN_le")
        self.horizontalLayout_11.addWidget(self.KdNN_le)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.KdGeschl_cbox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.KdGeschl_cbox.setFont(font)
        self.KdGeschl_cbox.setObjectName("KdGeschl_cbox")
        self.KdGeschl_cbox.addItem("")
        self.KdGeschl_cbox.addItem("")
        self.horizontalLayout_2.addWidget(self.KdGeschl_cbox)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.FaN_le = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.FaN_le.setFont(font)
        self.FaN_le.setObjectName("FaN_le")
        self.horizontalLayout_6.addWidget(self.FaN_le)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.FaNErg_le = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.FaNErg_le.setFont(font)
        self.FaNErg_le.setObjectName("FaNErg_le")
        self.horizontalLayout_7.addWidget(self.FaNErg_le)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.Anschr_le = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.Anschr_le.setFont(font)
        self.Anschr_le.setObjectName("Anschr_le")
        self.horizontalLayout_8.addWidget(self.Anschr_le)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        self.PLZ_le = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.PLZ_le.setFont(font)
        self.PLZ_le.setObjectName("PLZ_le")
        self.horizontalLayout_10.addWidget(self.PLZ_le)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        self.St_le = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.St_le.setFont(font)
        self.St_le.setObjectName("St_le")
        self.horizontalLayout_13.addWidget(self.St_le)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayoutWidget_17 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(10, 270, 451, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.horizontalLayoutWidget_17.setFont(font)
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_17)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_15.addWidget(self.label_16)
        self.StdPr_le = QtWidgets.QLineEdit(self.horizontalLayoutWidget_17)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.StdPr_le.setFont(font)
        self.StdPr_le.setObjectName("StdPr_le")
        self.horizontalLayout_15.addWidget(self.StdPr_le)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_17)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_16.addWidget(self.label_17)
        self.gesStd_le = QtWidgets.QLineEdit(self.horizontalLayoutWidget_17)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.gesStd_le.setFont(font)
        self.gesStd_le.setObjectName("gesStd_le")
        self.horizontalLayout_16.addWidget(self.gesStd_le)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_15)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(10, 410, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.Abs_le = QtWidgets.QLineEdit(self.centralwidget)
        self.Abs_le.setGeometry(QtCore.QRect(90, 410, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.Abs_le.setFont(font)
        self.Abs_le.setObjectName("Abs_le")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(-120, 550, 310, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 550, 451, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(500, 380, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_21.setObjectName("label_21")
        self.LBpath_le = QtWidgets.QLineEdit(self.centralwidget)
        self.LBpath_le.setGeometry(QtCore.QRect(500, 420, 411, 21))
        self.LBpath_le.setObjectName("LBpath_le")
        self.LBpathbw_btn = QtWidgets.QPushButton(self.centralwidget)
        self.LBpathbw_btn.setGeometry(QtCore.QRect(920, 420, 75, 23))
        self.LBpathbw_btn.setObjectName("LBpathbw_btn")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(500, 430, 310, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.out_dic_le = QtWidgets.QLineEdit(self.centralwidget)
        self.out_dic_le.setGeometry(QtCore.QRect(500, 490, 411, 21))
        self.out_dic_le.setObjectName("out_dic_le")
        self.Outpathbw_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Outpathbw_btn.setGeometry(QtCore.QRect(920, 490, 75, 23))
        self.Outpathbw_btn.setObjectName("Outpathbw_btn")
        self.DB_btn = QtWidgets.QPushButton(self.centralwidget)
        self.DB_btn.setGeometry(QtCore.QRect(890, 20, 111, 41))
        self.DB_btn.setObjectName("DB_btn")
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(330, 580, 131, 41))
        self.clear_btn.setObjectName("clear_btn")
        self.onePDF_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.onePDF_cb.setGeometry(QtCore.QRect(710, 580, 92, 23))
        self.onePDF_cb.setChecked(True)
        self.onePDF_cb.setObjectName("onePDF_cb")
        self.LB_format_cb = QtWidgets.QComboBox(self.centralwidget)
        self.LB_format_cb.setGeometry(QtCore.QRect(660, 385, 86, 25))
        self.LB_format_cb.setObjectName("LB_format_cb")
        self.LB_format_cb.addItem("")
        self.LB_format_cb.addItem("")
        self.test_btn = QtWidgets.QPushButton(self.centralwidget)
        self.test_btn.setGeometry(QtCore.QRect(80, 590, 89, 25))
        self.test_btn.setObjectName("test_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1040, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RFFE_Vorlage_Schreiber"))
        self.PDFG_btn.setText(_translate("MainWindow", "PDF erstellen"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ff0000;\">AngbotsInfo</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Bezeichnung"))
        self.Bez_te.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\">TestBez</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Nr."))
        self.Nr_le.setText(_translate("MainWindow", "A123"))
        self.label_8.setText(_translate("MainWindow", "Gültigkeitsdauer"))
        self.Gd_cbox.setItemText(0, _translate("MainWindow", "10"))
        self.Gd_cbox.setItemText(1, _translate("MainWindow", "14"))
        self.label_4.setText(_translate("MainWindow", "Tag(e)"))
        self.label_7.setText(_translate("MainWindow", "Anlaufsdatum"))
        self.AnlD_de.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">KundenInfo</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "Titel"))
        self.titel_cbox.setItemText(1, _translate("MainWindow", "Dr.-Ing."))
        self.titel_cbox.setItemText(2, _translate("MainWindow", "Prof."))
        self.titel_cbox.setItemText(3, _translate("MainWindow", "Dipl.-Ing."))
        self.label_2.setText(_translate("MainWindow", "VN"))
        self.KdVN_le.setText(_translate("MainWindow", "Till"))
        self.label_10.setText(_translate("MainWindow", "NN"))
        self.KdNN_le.setText(_translate("MainWindow", "Schiffmann"))
        self.label.setText(_translate("MainWindow", "Geschl"))
        self.KdGeschl_cbox.setItemText(0, _translate("MainWindow", "M"))
        self.KdGeschl_cbox.setItemText(1, _translate("MainWindow", "F"))
        self.label_11.setText(_translate("MainWindow", "Fa.Name"))
        self.FaN_le.setText(_translate("MainWindow", "Musterfirmaname"))
        self.label_12.setText(_translate("MainWindow", "Fa.NameErg"))
        self.FaNErg_le.setText(_translate("MainWindow", "MusterfirmannameErg"))
        self.label_13.setText(_translate("MainWindow", "Anschrift"))
        self.Anschr_le.setText(_translate("MainWindow", "Gustav-Freytag-str.35"))
        self.label_14.setText(_translate("MainWindow", "PLZ"))
        self.PLZ_le.setText(_translate("MainWindow", "1111"))
        self.label_15.setText(_translate("MainWindow", "Stadt"))
        self.St_le.setText(_translate("MainWindow", "Berlin"))
        self.label_16.setText(_translate("MainWindow", "Stundenpreis"))
        self.StdPr_le.setText(_translate("MainWindow", "Stdpreis"))
        self.label_17.setText(_translate("MainWindow", "gesamte Stunden"))
        self.gesStd_le.setText(_translate("MainWindow", "33,33"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">Absender</span></p></body></html>"))
        self.Abs_le.setText(_translate("MainWindow", "Chen from Future"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ff0000;\">Testing</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "Leistungsbeschreibung"))
        self.LBpathbw_btn.setText(_translate("MainWindow", "browse"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">Output_Dir</span><br/></p></body></html>"))
        self.Outpathbw_btn.setText(_translate("MainWindow", "browse"))
        self.DB_btn.setText(_translate("MainWindow", "DB"))
        self.clear_btn.setText(_translate("MainWindow", "Clear"))
        self.onePDF_cb.setText(_translate("MainWindow", "One PDF"))
        self.LB_format_cb.setItemText(0, _translate("MainWindow", "PDF"))
        self.LB_format_cb.setItemText(1, _translate("MainWindow", "txt/tex"))
        self.test_btn.setText(_translate("MainWindow", "test"))

    def __init__(self):
        super(Ui_AngWindow, self).__init__()
        self.setupUi(self)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_AngWindow()
    ui.show()
    sys.exit(app.exec_())