# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestMainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 138)
        MainWindow.setMouseTracking(True)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ok_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ok_btn.setGeometry(QtCore.QRect(590, 30, 181, 31))
        self.ok_btn.setObjectName("ok_btn")
        self.tp_cbox = QtWidgets.QComboBox(self.centralwidget)
        self.tp_cbox.setGeometry(QtCore.QRect(100, 30, 401, 31))
        self.tp_cbox.setObjectName("tp_cbox")
        self.tp_cbox.addItem("")
        self.tp_cbox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vorlage Auswählen"))
        self.ok_btn.setText(_translate("MainWindow", "OK"))
        self.tp_cbox.setItemText(0, _translate("MainWindow", "-----------Bitte eine Vorlage auswählen-----------"))
        self.tp_cbox.setItemText(1, _translate("MainWindow", "Angebot-Stundenpreis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
